### ISSUE TITLE
Getting key presses

### ISSUE THREAD

**Issue by tom-doerr** [AbhiK002/virtual-keyboard#1]
Can I start this keyboard from my own python script and get the key presses in my script instead of sending them to the operating system?

**Comment by AbhiK002** [comment]
Hey Tom, you can surely start the keyboard from your own python script (by importing the class and using the `engine()` and `start()` methods as shown [here](https://github.com/AbhiK002/virtual-keyboard#usage)).
However, since the program uses the `keyboard` module, you can only send the keypresses to the OS for now. To make it send keypresses to a script, a new method instead of `engine()` will have to be created, depending on your script.

**Comment by tom-doerr** [comment]
Okay,  thank you for the information!On Jul 8, 2022 19:47, AbhineetK ***@***.***> wrote:
Hey Tom, you can surely start the keyboard from your own python script (by importing the class and using the engine() and start() methods as shown here).
However, since the program uses the keyboard module, you can only send the keypresses to the OS for now. To make it send keypresses to a script, a new method instead of engine() will have to be created, depending on your script.

**Comment by AbhiK002** [comment]
You're welcome! Have a great day ahead.
